site_name: Claude Artifacts
site_url: https://aapfeldorf.github.io/site
theme:
  name: material
  palette:
    scheme: slate
    primary: orange
    accent: deep orange
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
markdown_extensions:
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
extra_css:
  - stylesheets/extra.css
nav:
  - Overview: index.md
  - Use Cases:
    - Coding: coding-uses.md
    - Data Visualization: data-visualization.md
    - Document Templates: document-templates.md
  - Ethical Implications: ethics.md
  - About: about.md